#pragma once
#define ROAD_SIZE 100
#define AMOUNT_VEHICLES 20
#define V_MAX 5
#define TIME_STEPS 20
#define DECELERATE_CHANCE 20
#define MIN_SPEED_RANDOM_DECELERATE 2
#define PLUSBUS_LENGTH 5
#define AMOUNT_ROADS 5
#define AMOUNT_NODES 10
#define AMOUNT_LINKS 10
#define NODE_NAME_MAX_SIZE 10

